### ISSUE TITLE
Start shift code marking people unavailable in logs incorrectly

### ISSUE THREAD

**Issue by brainomite** [MutualAidNYC/mutual-aid-call-center#57]
An example of this occurrence can be found [here](https://airtable.com/tbl4o76Y6sf3X5wiO/viwuMCKjCK4wKuKJ8/recQC20IYckXMigs4)

observation, only the log is incorrect, workers are actually being marked available

**Comment by brainomite** [comment]
Adding some log statements to see what is being sent to airtable

**Comment by dlobraico** [comment]
Hasn't been an issue in a while, closing.
