### ISSUE TITLE
New users are not always being auto-setup correctly

### ISSUE THREAD

**Issue by brainomite** [MutualAidNYC/mutual-aid-call-center#71]
Symptoms:
The worker is added to the Airtable table, `Controls - Phone System Volunteers`: After the sync code runs, there is an inconsistent status where the worker is created in Taskrouter, but the fact that it was created isn't reported back to the Airtable table by updating the worker sid.
The next time it is run, it causes an error because it attempts to create the user a second time, and there cannot be two users with the same name (we have a random set of characters for every user to make them unique)

This has happened a 2nd time now. After the first, I didn't put any logging in as I forgot all about it.

Error code can be found in slack, sorry there is PII, [here](https://mutualaidnyc.slack.com/archives/G012C8WCYRL/p1601308090001800?thread_ts=1601308044.001700&cid=G012C8WCYRL):

**Comment by brainomite** [comment]
Entry for the worker sync code can be found [here](https://github.com/MutualAidNYC/mutual-aid-call-center/blob/37a89726b7416fb355920da28204692a6cc42487/src/jobs/syncWorkers.js#L1):

Integromat runs this code everyday workday at noon, eastern time
One can manually trigger it live from the Heroku console by running `node ./src/jobs/syncWorker.js`

**Comment by dlobraico** [comment]
I think this has since been resolved, closing until it recurs.
